x-redis-env: &redis-env
  REDIS_HOST: $REDIS_HOST
  REDIS_PORT: $REDIS_PORT

services:
  script_db:
    build:
      dockerfile: ./compose/scripts/Dockerfile
    command: bash -c "./run.bash scripts/upload_db.py $ENVIRONMENT mhdle"
    depends_on:
      - $REDIS_HOST
    environment:
      <<: *redis-env
      ENVIRONMENT: $ENVIRONMENT
    image: kyledle_script_db:$ENVIRONMENT
    networks:
      - redisnet