x-celery-env: &celery-env
  CELERY_BROKER_URL: redis://$REDIS_USERNAME:$REDIS_PASSWORD@$REDIS_HOST:6379/0
  CELERY_RESULT_BACKEND: redis://$REDIS_USERNAME:$REDIS_PASSWORD@$REDIS_HOST:6379/0

services:
  backend:
    command: sh -c "python -c 'import tasks; tasks.schedule_levels(tomorrow=False)' && gunicorn --bind 0.0.0.0:5000 --workers 3 main:app"
    env_file:
      - .env/.env.$ENVIRONMENT
    networks:
      - backend_network
    ports: !reset null

  redis:
    command: redis-server /etc/redis/kyledle/redis.conf
    volumes:
      - ./redis.conf:/etc/redis/kyledle/redis.conf

  celery_worker:
    command: celery -A config.celery worker --loglevel INFO --uid=nobody --gid=nogroup
    env_file:
      - .env/.env.$ENVIRONMENT
    environment:
      <<: *celery-env

  celery_beat:
    command: sh -c "chown nobody:nogroup celerybeat-schedule && celery -A config.celery beat --loglevel INFO --uid=nobody --gid=nogroup"
    env_file:
      - .env/.env.$ENVIRONMENT
    environment:
      <<: *celery-env

  nginx:
    container_name: ${PROJECT_NAME}_${ENVIRONMENT}_nginx
    depends_on:
      - backend
    image: nginx:alpine
    networks:
      - backend_network
    ports:
      - $BACKEND_PORT:80
    volumes:
      - ./nginx/nginx-backend.conf:/etc/nginx/nginx.conf

networks:
  backend_network:
