x-celery-env: &celery-env
  CELERY_BROKER_URL: redis://$REDIS_HOST:6379/0
  CELERY_RESULT_BACKEND: redis://$REDIS_HOST:6379/0

x-redis-env: &redis-env
  REDIS_HOST: $REDIS_HOST

services:
  web:
    build:
      dockerfile: ./compose/backend/Dockerfile
    command: flask run --host=0.0.0.0
    depends_on:
      - $REDIS_HOST
    environment:
      <<: *redis-env
      ENVIRONMENT: $ENVIRONMENT
      FLASK_APP: main:app
      FLASK_DEBUG: 1
    image: kyledle_flask:$ENVIRONMENT
    networks:
      - redisnet
    ports:
      - $WEB_PORT:5000
    volumes:
      - ./backend/src:/src

  redis:
    image: redis:alpine
    ports:
      - $REDIS_PORT:6379
    networks:
      - redisnet
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      dockerfile: ./compose/backend/Dockerfile
    command: watchmedo auto-restart --directory=/src -- celery -A config.celery worker --loglevel DEBUG --uid=nobody --gid=nogroup
    depends_on:
      - $REDIS_HOST
    environment:
      <<: [*celery-env, *redis-env]
      ENVIRONMENT: $ENVIRONMENT
    image: kyledle_celery_worker:$ENVIRONMENT
    networks:
      - redisnet
    volumes:
      - ./backend/src:/src

  celery_beat:
    build:
      dockerfile: ./compose/backend/Dockerfile
    command: watchmedo auto-restart --directory=/src -- celery -A config.celery beat --loglevel DEBUG --uid=nobody --gid=nogroup
    depends_on:
      - $REDIS_HOST
    environment:
      <<: [*celery-env, *redis-env]
      ENVIRONMENT: $ENVIRONMENT
    image: kyledle_celery_beat:$ENVIRONMENT
    networks:
      - redisnet
    volumes:
      - ./backend/src:/src

networks:
  redisnet:

volumes:
    redis_data:
