x-celery-env: &celery-env
  CELERY_BROKER_URL: redis://$REDIS_USERNAME:$REDIS_PASSWORD@$REDIS_HOST:6379/0
  CELERY_RESULT_BACKEND: redis://$REDIS_USERNAME:$REDIS_PASSWORD@$REDIS_HOST:6379/0

services:
  backend:
    command: sh -c "python -c 'import tasks; tasks.schedule_levels(tomorrow=False)' && gunicorn --bind 0.0.0.0:5000 --workers 3 main:app"
    env_file:
      - .env/.env.$ENVIRONMENT
    networks:
      - nginx_network

  redis:
    command: redis-server /etc/redis/kyledle/redis.conf
    volumes:
      - ./redis.conf:/etc/redis/kyledle/redis.conf

  celery_worker:
    command: celery -A config.celery worker --loglevel INFO
    env_file:
      - .env/.env.$ENVIRONMENT
    environment:
      <<: *celery-env

  celery_beat:
    command: celery -A config.celery beat --loglevel INFO
    env_file:
      - .env/.env.$ENVIRONMENT
    environment:
      <<: *celery-env

networks:
  nginx_network:
    external: true
    name: $NGINX_NETWORK
