x-celery-env: &celery-env
  CELERY_BROKER_URL: redis://$REDIS_USERNAME:$REDIS_PASSWORD@$REDIS_HOST:$REDIS_PORT/0
  CELERY_RESULT_BACKEND: redis://$REDIS_USERNAME:$REDIS_PASSWORD@$REDIS_HOST:$REDIS_PORT/0

services:
  web:
    command: gunicorn --bind 0.0.0.0:5000 --workers 3 main:app
    networks:
      - webnet
  redis:
    command: redis-server /etc/redis/redis.conf --port $REDIS_PORT
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
  celery_worker:
    command: celery -A config.celery worker --loglevel INFO
    environment:
      <<: *celery-env
  celery_beat:
    command: celery -A config.celery beat --loglevel INFO
    environment:
      <<: *celery-env
  nginx:
    depends_on:
      - web
    image: nginx:alpine
    networks:
      - webnet
    ports:
      - $NGINX_PORT:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  webnet:
