dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  state_extended: ^4.18.0
  google_fonts: ^6.2.1
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  timezone: ^0.9.4
  intl: ^0.19.0
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
environment:
  sdk: '>=3.4.3 <4.0.0'
flutter:
  assets:
  - assets/
  uses-material-design: true
name: kyledle
publish_to: 'none'
version: 1.0.0+1
